// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"TMBtnPicture","status":true,"description":"ピクチャをタップ（クリック）でコモンイベントを起動します。","parameters":{}},
{"name":"Yami_SkipTitle","status":true,"description":"テストプレイ用にタイトルシーンを飛ばすことができます。","parameters":{}},
{"name":"liply_ErrorDetail","status":true,"description":"Print copyable detailed error","parameters":{}},
{"name":"liply_SceneCache","status":false,"description":"Scene Cache System","parameters":{"WebGL":"0","Report Memory":"0"}},
{"name":"liply_WaitForImage","status":false,"description":"","parameters":{}},
{"name":"liply_iOS_Video","status":false,"description":"","parameters":{}},
{"name":"liply_onBitmapLoad_patch","status":false,"description":"","parameters":{}},
{"name":"CustomizeConfigDefault","status":true,"description":"オプションデフォルト値設定プラグイン","parameters":{"常時ダッシュ":"OFF","コマンド記憶":"OFF","BGM音量":"80","BGS音量":"80","ME音量":"80","SE音量":"100","常時ダッシュ消去":"OFF","コマンド記憶消去":"OFF","BGM音量消去":"OFF","BGS音量消去":"OFF","ME音量消去":"OFF","SE音量消去":"OFF"}},
{"name":"liply_ControlSkip","status":false,"description":"liply_ControlSkip","parameters":{"Skip":"0"}},
{"name":"Text_Centering","status":true,"description":"","parameters":{}},
{"name":"AtsumaruAutoplayFix","status":true,"description":"すべてのブラウザで自動再生起因による動画再生の失敗を修正するプラグインです。 コアスクリプトの https://github.com/rpgtkoolmv/corescript/pull/140 こちらの修正の先行実装になります。","parameters":{}},
{"name":"dwango_androidpatch","status":true,"description":"Android Chromeで音が鳴らない問題を解決するプラグイン","parameters":{}},
{"name":"liply_fixParallax","status":true,"description":"parallaxループしすぎるとおかしくなるバグを修正します","parameters":{}},
{"name":"liply_PictureAnimation","status":true,"description":"ピクチャのフレームアニメーションを可能にするプラグインです。","parameters":{}},
{"name":"EasingPicture","status":true,"description":"ピクチャーの移動パターンを増やします。","parameters":{}},
{"name":"DestinationSprite","status":true,"description":"v1.2.3 - With this plugin you can change the destination place sprite of the mouse\\touch input.\r\n<DestinationSprite>","parameters":{"Sprite Figure":"Square","Custom Image":"image","Animation mode":"blink","Fade speed":"0","Sprite Size":"0","Sprite Color":"#ffffff","Sprite Opacity":"0","Sprite Blend":"1"}},
{"name":"liply_memoryleak_patch","status":true,"description":"メモリリークパッチ","parameters":{}}
];
